# Generated by Django 4.1.4 on 2022-12-27 23:22

from django.db import migrations, models
import mensajes.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, default='sinperfil.png', upload_to=mensajes.models.create_path),
        ),
    ]
