# Generated by Django 4.1.4 on 2022-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_usuarios_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, default='sinperfil.png', upload_to='static/media/'),
        ),
    ]
